[tox]
exitfirst = true
envlist = py38, py39, py311, py312, py314

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
    QT_QPA_PLATFORM = offscreen
deps =
    -r{toxinidir}/requirements_test.txt
    -r{toxinidir}/requirements.txt
commands_pre =
    pip uninstall -y pytest-xvfb pyvirtualdisplay
commands =
    python -m pytest -x --basetemp={envtmpdir}
